### ISSUE TITLE
go-cqhttp协议更新导致rjson报错

### ISSUE THREAD

**Issue by CNlongY-Py** [CNlongY-Py/SimpQ-Bot#1]
Traceback (most recent call last):
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2548, in __call__
    return self.wsgi_app(environ, start_response)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2528, in wsgi_app
    response = self.handle_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 2525, in wsgi_app
    response = self.full_dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1822, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1820, in full_dispatch_request
    rv = self.dispatch_request()
  File "/usr/local/lib/python3.10/dist-packages/flask/app.py", line 1796, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "/home/ubuntu/main.py", line 14, in main
    bot.initData(request.get_json())
  File "/home/ubuntu/bot.py", line 267, in initData
    if rjson:

**Comment by CNlongY-Py** [comment]
社区群已发布临时补丁,具体bug将于c0.1-RC2修复
